
# Site title
title: "Jack's Portfolio"

# Below the site title
tagline: "I'm Jack Matthews, I'm a recent bSC cybersecurity graduate from the University of West London and am currently searching for work in the field of IT. I'm eager to further my understanding of cybersecurity and to demonstrate my knowlege to you."

# Site logo
logo:

# A description of your site for social meta tag, search engines, and feed.xml
description: |

# The base hostname & protocol of your site for where absolute urls are needed
url: https://blogbox.netlify.app

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:

- text: "About me"
  url: /about/
- text: "Projects"
  url: /Projects/
- text: "Experience"
  url: /Experience/
- text: "Contacts"
  url: /Contacts/

# Author information - author info at the bottom of the post
author_name: "Jack Matthews"
author_bio: "My name is Jack Mattehws and I'm a bSC cybersecurity graduate from the University of West London."
author_url: "https://JacksAGit25.github.io"
author_location: "Vilnius, Lithuania"
author_image: authorimage.jpg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://JacksAGit25.github.io/

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "jackprmatt25@gmail.com"

# Social links in the site footer
linkedin_username: "linkedin.com/in/jack-matthews-a3728b2a4"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
