
# Site title
title: "Jack's Portfolio"

# Below the site title
tagline: "I'm Jack Matthews, I'm a recent bSC cybersecurity graduate from the University of West London and am currently searching for work in the field of IT. I'm eager to further my understanding of cybersecurity and look forward to demonstrating my ability."

   "Email"
"jackprmatt25@gmail.com"

image: Github_Social.png
image: LinkedIn_Social.png
image: Facebook_Social.png


# Site logo
logo: CyberLogo.png


# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl:

sass:
  sass_dir: _sass

# Site navigation - each item must have a title and a url.
navigation:

- text: "About me"
  url: /about/
- text: "Projects"
  url: /Projects/
- text: "Experience"
  url: /Experience/
- text: "Contacts"
  url: /Contacts/

# Author information - author info at the bottom of the post
author_name: "Jack Matthews"
author_bio: "My name is Jack Mattehws and I'm a bSC cybersecurity graduate from the University of West London."
author_url: "https://JacksAGit25.github.io"
author_image: Profile_picture.jpeg

# Footer ad banner
banner_image: banner.jpg
banner_url: https://JacksAGit25.github.io/

# Footer newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "jackprmatt25@gmail.com"


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
